name: Build

on:
  push:
    branches:
      - 5-feat-add-build-step-in-action

permissions:
  contents: read

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.tags.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Tags
        id: tags
        run: python tags.py

  build:
    runs-on: ubuntu-latest
    needs: get-tags
    strategy:
      matrix: ${{fromJson(needs.get-tags.outputs.matrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Separate file and tag
        id: tag
        run: |
          echo "dockerfile=$(echo ${{ matrix.tags }} | cut -d ',' -f 1)" >> $GITHUB_OUTPUT
          echo "tag=$(echo ${{ matrix.tags }} | cut -d ',' -f 2)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ steps.tag.outputs.dockerfile }}
          push: true
          tags: jljl1337/jenkins-docker:${{ steps.tag.outputs.tag }}
