name: Build

on:
  push:
    branches:
      - 1-feat-get-all-tags-to-be-built

permissions:
  contents: read

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.tags.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Tags
        id: tags
        run: python tags.py

  build:
    runs-on: ubuntu-latest
    needs  get-tags:
    strategy:
      matrix: ${{fromJson(needs.get-tags.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: echo "Testing ${{ matrix.tags }}"
